version: "3.7"

services:
  testdatagenerator:
    image: docker.miracum.org/fhir/fhir-generator:v1.5.0
    volumes:
      - ./config:/opt/testdata-generator/src/config
      - ./input:/opt/testdata-generator/input
      - ./output:/opt/testdata-generator/output
